image: outrigger/gitlab-ci-workspace:stable

services:
  - docker:dind

variables:
  # Ensure fast file system is used for docker:dind
  DOCKER_DRIVER: overlay2
  # PROJECT_NAME is ideally set in the CI/CD variables instead of declared here
  # PROJECT_NAME: PUT_PROJECT_NAME_HERE

  # KUBE_NAMESPACE is set in the CI/CD variables instead of declared here
  # Normally PROJECT_NAME-project
  # KUBE_NAMESPACE: PUT_NAMESPACE_HERE

  # CI_REGISTRY_IMAGE isn't used directly to structurally allow for projects
  # with multiple images which may need to be built. However, the majority are
  # expected to only ever need to build one image.
  WEB_IMAGE: ${CI_REGISTRY_IMAGE}/web

  # Set the release name
  # This has to match how things line up in the deploy script
  RELEASE_NAME: ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}

  # By default the environment name is set to the branch name.
  # If you need this to be different, you'll need to create additional jobs
  # specific to each different environment.
  PROJECT_ENV: ${CI_COMMIT_REF_SLUG}

  # Specify the name of the main branch to use as starting cache for building
  # feature branches
  # MAIN_BRANCH: qa
  MAIN_BRANCH: master

stages:
  # tasks are intended for items which are only run manually and don't need
  # a build to succeed in order to be able to execute. The idea is that they
  # are always skipped in any automatic activities but come before a build so
  # that if it fails it doesn't effect the ability to run a task
  - tasks
  - build
  - validate
  - deploy
  - update
  - test
  - notify
  - cleanup

before_script:
  # Dump environment so we know what variables and values we have to work with.
  - set
  # Sanity check to make sure the project is configured.
  - ./.gitlab-ci/bin/check-settings.sh
  # Ensure DOCKER_HOST is set in runner.
  - source ./.gitlab-ci/bin/check-docker.sh
  # Define project-specific environment variables.
  - source .env

# This job builds the code base pushes a docker image to the GitLab registry.
# This is only needed if we will spin up a K8S environment for the image.
build:
  stage: build
  script:
    # Call common deploy script.  Should not need to modify.
    - .gitlab-ci/bin/build.sh
    # Add any post-build commands here, such as flowdock notifications
    # - ./.gitlab-ci/bin/flowdock-notify.sh "Build complete for ${CI_COMMIT_TITLE} to ${CI_ENVIRONMENT_URL}"
  cache:
    key: ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - build
      - vendor
      - project/themes/*/node_modules
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Run validation (linting) and unit tests on already built codebase.
validate:
  stage: validate
  script:
    - docker-compose -f .gitlab-ci/build.yml run --rm base ./bin/validate
    - docker-compose -f .gitlab-ci/build.yml run --rm base ./bin/test unit,kernel
  cache:
    key: ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
    paths:
      - build
      - vendor
      - project/themes/*/node_modules
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Runs when a feature/* branch is commited/pushed.
# Doesn't create any environment, so just build, lint, and unit test.
validate_feature:
  stage: validate
  script:
    # assemble the codebase
    - docker-compose -f .gitlab-ci/build.yml run --rm base ./bin/make -y
    # Run linting etc.
    - docker-compose -f .gitlab-ci/build.yml run --rm base ./bin/validate
    # Run unit tests.
    - docker-compose -f .gitlab-ci/build.yml run --rm base ./bin/test unit,kernel
  cache:
    # Pull the cache from the main branch.
    # Speeds up feature branch build so not starting from scratch.
    key: ${PROJECT_NAME}-${MAIN_BRANCH}
    # Prevent cache from being updated/pushed.
    policy: pull
    paths:
      - build
      - vendor
      - project/themes/*/node_modules
  only:
    - /^feature/

# Deploy the a branch to an environment.
# Use this job if your branch names match your environment names.
# e.g. branch "master" has environment www.PROJECT_NAME.master.kube.p2devcloud.com
# If you need different names, see the branch-specific deploy jobs below.
deploy:
  stage: deploy
  environment:
    # Cannot use environment variables here, only gitlab variables.
    # Also cannot use $PROJECT_ENV since GitLab doesn't support vars in vars.
    name: ${CI_COMMIT_REF_SLUG}
    url: http://www.${CI_COMMIT_REF_SLUG}.${PROJECT_NAME}.kube.p2devcloud.com
    on_stop: x_destroy_env
  script:
    # Call common deploy script.  Should not need to modify.
    - .gitlab-ci/bin/deploy.sh
    # Add any post-deploy commands here, such as flowdock notifications
    # - ./.gitlab-ci/bin/flowdock-notify.sh "Deployment complete for ${CI_COMMIT_TITLE} to ${CI_ENVIRONMENT_URL}"
  artifacts:
    # Save the manifests from the deployment so it can be deleted later.
    name: ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-manifests
    # Don't expire these since normal environments might be long running.
    paths:
      - .gitlab-ci/manifests
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Install and test a feature branch manually.
deploy_feature:
  stage: deploy
  variables:
    PROJECT_ENV: feature-${CI_COMMIT_SHORT_SHA}
    RELEASE_NAME: ${PROJECT_NAME}-feature-${CI_COMMIT_SHORT_SHA}
  environment:
    # Cannot use environment variables here, only gitlab variables.
    # Also cannot use $PROJECT_ENV since GitLab doesn't support vars in vars.
    name: feature-${CI_COMMIT_SHORT_SHA}
    url: http://www.feature-${CI_COMMIT_SHORT_SHA}.${PROJECT_NAME}.kube.p2devcloud.com
    on_stop: x_destroy_feature
  script:
    # Call common deploy script.  Should not need to modify.
    # Skips the octane setup since already done in main branch cache.
    - .gitlab-ci/bin/build.sh -skip
    # Call common deploy script.  Should not need to modify.
    - .gitlab-ci/bin/deploy.sh
    # Fresh install for feature branches being tested.
    - ./.gitlab-ci/bin/exec.sh cli /var/www/bin/install -y
    - ./.gitlab-ci/bin/exec.sh cli /var/www/bin/test
  artifacts:
    # Save the manifests from the deployment so it can be deleted later.
    name: ${PROJECT_NAME}-feature-${CI_COMMIT_SHORT_SHA}-manifests
    # Expire these since feature-branch environments are not long-lived.
    expire_in: 1 week
    paths:
      - .gitlab-ci/manifests
  cache:
    # Pull the cache from the main branch.
    # Speeds up feature branch build so not starting from scratch.
    key: ${PROJECT_NAME}-${MAIN_BRANCH}
    # Prevent cache from being updated/pushed.
    policy: pull
    paths:
      - build
      - vendor
      - project/themes/*/node_modules
  only:
    # Set the branch for the environment here.
    - /^feature/
  when: manual

# Deploy the an environment with a different branch name.
# Use this job if your want a different environment name for a branch.
# Change "ENV" to the name of the environment, and "BRANCH" to the branch.
# NOTE: You will also need to duplicate any other job that accesses the
#    environment, such as the "update" and "test" jobs to specify the
#    environment.name value for each one.
#
# deploy_ENV:
#   stage: deploy
#   variables:
#     # Set the name of the desired environment here.
#     PROJECT_ENV: ENV
#   environment:
#     # Cannot use environment variables here, only gitlab variables.
#     name: ${PROJECT_ENV}
#     url: http://www.${PROJECT_ENV}.${PROJECT_NAME}.kube.p2devcloud.com
#   script:
#     # Call common deploy script.  Should not need to modify.
#     - .gitlab-ci/bin/deploy.sh
#   cache:
#     key: ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-manifest
#     paths:
#       - .gitlab-ci/manifests
#   only:
#     # Set the branch for the environment here.
#     - /^BRANCH/

# Update the environment.
# Installs Drupal if needed, runs update hooks, config-import, clear-cache.
update:
  stage: update
  environment:
    # Cannot use environment variables here, only gitlab variables.
    # Also cannot use $PROJECT_ENV since GitLab doesn't support vars in vars.
    name: ${CI_COMMIT_REF_SLUG}
    url: http://www.${CI_COMMIT_REF_SLUG}.${PROJECT_NAME}.kube.p2devcloud.com
  script:
    # Useful debugging to see if drush is happy.
    - ./.gitlab-ci/bin/exec.sh cli drush status
    - ./.gitlab-ci/bin/exec.sh cli /var/www/bin/import -y
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Run full test suite that needs the running environment.
test:
  stage: test
  environment:
    name: ${CI_COMMIT_REF_SLUG}
  script:
    - ./.gitlab-ci/bin/exec.sh cli /var/www/bin/test
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Manual task to reinstall Drupal when needed.
install:
  stage: tasks
  environment:
    name: ${CI_COMMIT_REF_SLUG}
  script:
    - ./.gitlab-ci/bin/exec.sh cli /var/www/bin/install -y
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/
  when: manual

# Purge the Kubernetes environment manually when needed.
# Set up as the stop action for deploy job, so stage needs to be deploy.
x_destroy_env:
  stage: cleanup
  variables:
    # Tells Gitlab not to bother doing a git-pull for this job.
    GIT_STRATEGY: none
  environment:
    # Cannot use environment variables here, only gitlab variables.
    # Also cannot use $PROJECT_ENV since GitLab doesn't support vars in vars.
    name: ${CI_COMMIT_REF_SLUG}
    url: http://www.${CI_COMMIT_REF_SLUG}.${PROJECT_NAME}.kube.p2devcloud.com
    action: stop
  script:
    # Remove everything that was deployed for this environment.
    - kubectl delete --recursive --filename .gitlab-ci/manifests
  dependencies:
    # Bring in the manifest artifact
    - deploy
  only:
    - /^qa/
    - /^test/
  allow_failure: true
  when: manual

# Purge the feature branch Kubernetes environment manually when needed.
# Set up as the stop action for feature_test job, so stage needs to be deploy.
x_destroy_feature:
  stage: cleanup
  variables:
    # Tells Gitlab not to bother doing a git-pull for this job.
    GIT_STRATEGY: none
  variables:
    PROJECT_ENV: feature-${CI_COMMIT_SHORT_SHA}
    RELEASE_NAME: ${PROJECT_NAME}-feature-${CI_COMMIT_SHORT_SHA}
  environment:
    # Cannot use environment variables here, only gitlab variables.
    # Also cannot use $PROJECT_ENV since GitLab doesn't support vars in vars.
    name: feature-${CI_COMMIT_SHORT_SHA}
    url: http://www.feature-${CI_COMMIT_SHORT_SHA}.${PROJECT_NAME}.kube.p2devcloud.com
    action: stop
  script:
    # Remove everything that was deployed for this environment.
    - kubectl delete --recursive --filename .gitlab-ci/manifests
  dependencies:
    # Bring in the manifest artifact
    - deploy_feature
  only:
    - /^feature/
  allow_failure: true
  when: manual

# Notify when pipeline succeeds.
success:
  stage: notify
  script:
    # Notify Flowdock that pipeline finished successfully.
    - ./.gitlab-ci/bin/flowdock-notify.sh ":green_heart:Deployment successful for [${CI_COMMIT_SHORT_SHA}](${CI_PIPELINE_URL}) ${CI_COMMIT_TITLE} to ${PROJECT_ENV}"
  when: on_success
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Notify when main pipeline branches fails.
failure:
  stage: notify
  script:
    # Send failure notification to main Flow with emoji.
    - ./.gitlab-ci/bin/flowdock-notify.sh ":broken_heart:Deployment failed for [${CI_COMMIT_SHORT_SHA}](${CI_PIPELINE_URL}) ${CI_COMMIT_TITLE} to ${PROJECT_ENV}"
  when: on_failure
  only:
    - /^qa/
    - /^test/
    - /^develop/
    - /^master/

# Notify when feature branches succeeds.
success_branch:
  stage: notify
  script:
    # Send failure notification to flow inbox (no emoji allowed :( ).
    - ./.gitlab-ci/bin/flowdock-notify.sh inbox "Deployment PASSSED to ${PROJECT_ENV}" "for <a href="${CI_PIPELINE_URL}">${CI_COMMIT_SHORT_SHA}</a> ${CI_COMMIT_TITLE}"
  when: on_success
  only:
    - /^feature/

# Notify when feature branches fails.
failure_branch:
  stage: notify
  script:
    # Send failure notification to flow inbox (no emoji allowed :( ).
    - ./.gitlab-ci/bin/flowdock-notify.sh inbox "Deployment failed to ${PROJECT_ENV}" "for <a href="${CI_PIPELINE_URL}">${CI_COMMIT_SHORT_SHA}</a> ${CI_COMMIT_TITLE}"
  when: on_failure
  only:
    - /^feature/
